server:
  port: 8091

spring:
  application:
    name: payment-service
  main:
    banner-mode: off
  jpa:
    hibernate:
      ddl-auto: update # When you launch the application for the first time - switch "update" at "create"
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  zipkin:
    base-url: http://localhost:9411/


eureka:
  client:
    instance:
      hostname: localhost
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

logging:
  file:
    path: C:\Users\Yusuf\Desktop\order-payment\logs\microservice.log
